apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type : {{.Values.service.type }}
  selector:
    {{- include "blue_green_deployment.selectorLabels" . | nindent 4}}
  ports:
  - port: {{.Values.service.port  }}
    targetPort: {{.Values.service.targetPort }}
    protocol: {{.Values.service.protocol  }}
